import { type Profile } from '@/interfaces/profil';
import { BiLogoPostgresql } from 'react-icons/bi';
import { DiRedis, DiRubyRough } from 'react-icons/di';
import {
  FaAws,
  FaCss3Alt,
  FaDatabase,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaLinux,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaShieldAlt,
  FaStripeS,
  FaVuejs,
} from 'react-icons/fa';
import { IoLogoIonic } from 'react-icons/io';
import { IoLogoFigma, IoLogoJavascript } from 'react-icons/io5';
import { PiNetworkSlashDuotone } from 'react-icons/pi';
import { RiNextjsFill, RiTailwindCssFill } from 'react-icons/ri';
import {
  SiAngular,
  SiAnsible,
  SiAnthropic,
  SiAxios,
  SiBun,
  SiCloudflare,
  SiDbeaver,
  SiDrizzle,
  SiExpress,
  SiGnubash,
  SiGrafana,
  SiGraphql,
  SiHashicorp,
  SiHelm,
  SiJest,
  SiJira,
  SiK3S,
  SiKnexdotjs,
  SiKubernetes,
  SiMongodb,
  SiNuxtdotjs,
  SiOracle,
  SiPfsense,
  SiPostman,
  SiPrisma,
  SiPrometheus,
  SiTerraform,
  SiTrivy,
  SiTypescript,
} from 'react-icons/si';
import { TbBrandReactNative, TbBrandSocketIo, TbSettingsAutomation } from 'react-icons/tb';

export const categories = [
  'Langages de programmation',
  'Frontend & UI',
  'Backend & API',
  'Bases de données & ORM',
  'Infrastructure & DevOps',
  'Cybersécurité',
  'Outils & Environnement',
] as const;

const skills = [
  { name: 'Linux', logo: FaLinux, theme: ['Infrastructure & DevOps'] },
  { name: 'GNS3', logo: PiNetworkSlashDuotone, theme: ['Infrastructure & DevOps'] },
  { name: 'K3S', logo: SiK3S, theme: ['Infrastructure & DevOps'] },
  { name: 'Docker', logo: FaDocker, theme: ['Infrastructure & DevOps'] },
  { name: 'kubernetes', logo: SiKubernetes, theme: ['Infrastructure & DevOps'] },
  { name: 'HTML5', logo: FaHtml5, theme: ['Frontend & UI'] },
  { name: 'CSS3', logo: FaCss3Alt, theme: ['Frontend & UI'] },
  { name: 'Python', logo: FaPython, theme: ['Langages de programmation'] },
  { name: 'JavaScript', logo: IoLogoJavascript, theme: ['Langages de programmation'] },
  { name: 'TypeScript', logo: SiTypescript, theme: ['Langages de programmation'] },
  { name: 'Tailwindcss', logo: RiTailwindCssFill, theme: ['Frontend & UI'] },
  { name: 'IA', logo: SiAnthropic, theme: ['Outils & Environnement'] },
  { name: 'Axios', logo: SiAxios, theme: ['Backend & API'] },
  { name: 'Socket.io', logo: TbBrandSocketIo, theme: ['Backend & API'] },
  { name: 'Ruby', logo: DiRubyRough, theme: ['Langages de programmation'] },
  { name: 'PHP', logo: FaPhp, theme: ['Langages de programmation'] },
  { name: 'Ionic', logo: IoLogoIonic, theme: ['Frontend & UI'] },
  { name: 'Next.js', logo: RiNextjsFill, theme: ['Frontend & UI'] },
  { name: 'React', logo: FaReact, theme: ['Frontend & UI'] },
  { name: 'Angular', logo: SiAngular, theme: ['Frontend & UI'] },
  { name: 'React Native', logo: TbBrandReactNative, theme: ['Frontend & UI'] },
  { name: 'Node.js', logo: FaNodeJs, theme: ['Backend & API'] },
  { name: 'Vue.js', logo: FaVuejs, theme: ['Frontend & UI'] },
  { name: 'Nuxt.js', logo: SiNuxtdotjs, theme: ['Frontend & UI'] },
  { name: 'Express.js', logo: SiExpress, theme: ['Backend & API'] },
  { name: 'Elysia', logo: SiExpress, theme: ['Backend & API'] },
  { name: 'Bun', logo: SiBun, theme: ['Langages de programmation', 'Backend & API'] },
  { name: 'MongoDB', logo: SiMongodb, theme: ['Bases de données & ORM'] },
  { name: 'PostgreSql', logo: BiLogoPostgresql, theme: ['Bases de données & ORM'] },
  { name: 'DBeaver ', logo: SiDbeaver, theme: ['Bases de données & ORM'] },
  { name: 'Redis', logo: DiRedis, theme: ['Bases de données & ORM'] },
  { name: 'Stripe', logo: FaStripeS, theme: ['Backend & API'] },
  { name: 'Knex.js', logo: SiKnexdotjs, theme: ['Bases de données & ORM'] },
  { name: 'Objection.js', logo: FaDatabase, theme: ['Bases de données & ORM'] },
  { name: 'Kysely', logo: FaDatabase, theme: ['Bases de données & ORM'] },
  { name: 'Drizzle ORM', logo: SiDrizzle, theme: ['Bases de données & ORM'] },
  { name: 'Prisma', logo: SiPrisma, theme: ['Bases de données & ORM'] },
  { name: 'Postman', logo: SiPostman, theme: ['Outils & Environnement'] },
  { name: 'Jira/Trello', logo: SiJira, theme: ['Outils & Environnement'] },
  { name: 'Figma', logo: IoLogoFigma, theme: ['Outils & Environnement'] },
  { name: 'Git', logo: FaGitAlt, theme: ['Outils & Environnement'] },
  { name: 'Jest', logo: SiJest, theme: ['Outils & Environnement'] },
  { name: 'Prometheus', logo: SiPrometheus, theme: ['Infrastructure & DevOps'] },
  { name: 'Grafana', logo: SiGrafana, theme: ['Infrastructure & DevOps'] },
  { name: 'PfSense', logo: SiPfsense, theme: ['Cybersécurité'] },
  { name: 'Teleport', logo: FaShieldAlt, theme: ['Cybersécurité'] },
  { name: 'GraphQL', logo: SiGraphql, theme: ['Backend & API'] },
  { name: 'Bash', logo: SiGnubash, theme: ['Langages de programmation'] },
  { name: 'CI/CD', logo: TbSettingsAutomation, theme: ['Infrastructure & DevOps'] },
  { name: 'Terraform', logo: SiTerraform, theme: ['Infrastructure & DevOps'] },
  { name: 'AWS', logo: FaAws, theme: ['Infrastructure & DevOps'] },
  { name: 'Ansible', logo: SiAnsible, theme: ['Infrastructure & DevOps'] },
  { name: 'Helm', logo: SiHelm, theme: ['Infrastructure & DevOps'] },
  { name: 'Loki', logo: SiGrafana, theme: ['Infrastructure & DevOps'] },
  { name: 'Vault (HashiCorp)', logo: SiHashicorp, theme: ['Cybersécurité'] },
  { name: 'Cloudflare', logo: SiCloudflare, theme: ['Infrastructure & DevOps'] },
  { name: 'Oracle Cloud', logo: SiOracle, theme: ['Infrastructure & DevOps'] },
  { name: 'Trivy', logo: SiTrivy, theme: ['Cybersécurité'] },
] as const satisfies Profile.skill[];

export default skills;
