name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Utilise Node.js 18+ pour ESM

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Configure l'environnement Pages (supporte .mjs)
        with:
          static_site_generator: next
          # Si vous utilisez @v4 à la place, décommentez la ligne suivante :
          # generator_config_file: ./next.config.mjs

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js (Turbopack)
        run: npm run build --if-present -- --turbopack

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out # Dossier de sortie statique

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
