name: Deploy Next.js to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
          static_site_generator: next
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: setup-pages
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js
        run: npm run build
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
