name: Auto-deploy Vercel via Hook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Appeler la Deploy Hook Vercel
        uses: actions/http-client@v1
        with:
          url: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
          method: 'POST'
          headers: |
            Content-Type: application/json
