name: « Déploiement Vercel »

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déclenchement du Deploy Hook Vercel
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          echo "🔔 Déclenchement du hook Vercel..."
          curl --fail --silent "$VERCEL_DEPLOY_HOOK_URL"
