name: Auto-deploy Vercel via Hook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher la Deploy Hook Vercel
        uses: fjogeleit/http-request-action@v1.4.3
        with:
          url: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
          method: POST
          customHeaders: |
            Content-Type: application/json
